// Mocks generated by Mockito 5.4.6 from annotations
// in carlog/test/core/services/ai_parsing_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:carlog/core/services/settings_service.dart' as _i3;
import 'package:hive_ce/hive_ce.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i3.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<dynamic> get settingsBox =>
      (super.noSuchMethod(
            Invocation.getter(#settingsBox),
            returnValue: _FakeBox_0<dynamic>(
              this,
              Invocation.getter(#settingsBox),
            ),
          )
          as _i2.Box<dynamic>);

  @override
  _i4.Stream<String> get currencyStream =>
      (super.noSuchMethod(
            Invocation.getter(#currencyStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  _i4.Stream<String> get dateFormatStream =>
      (super.noSuchMethod(
            Invocation.getter(#dateFormatStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  String get currency =>
      (super.noSuchMethod(
            Invocation.getter(#currency),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
          )
          as String);

  @override
  String get dateFormat =>
      (super.noSuchMethod(
            Invocation.getter(#dateFormat),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#dateFormat),
            ),
          )
          as String);

  @override
  String get aiBaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#aiBaseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#aiBaseUrl),
            ),
          )
          as String);

  @override
  String get aiApiKey =>
      (super.noSuchMethod(
            Invocation.getter(#aiApiKey),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#aiApiKey),
            ),
          )
          as String);

  @override
  String get aiModel =>
      (super.noSuchMethod(
            Invocation.getter(#aiModel),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#aiModel),
            ),
          )
          as String);

  @override
  set settingsBox(_i2.Box<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#settingsBox, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCurrency(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrency, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDateFormat(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDateFormat, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setAiBaseUrl(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAiBaseUrl, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setAiApiKey(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAiApiKey, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setAiModel(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAiModel, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> detectAndSetCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#detectAndSetCurrency, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
